# from utils.helpers import generate_uuid

SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
DB_CONNECTION_STRING = "sqlite:///data.db"
SQL_MODIFICATION_STRING = "SQLALCHEMY_TRACK_MODIFICATIONS"
PROPAGATE_EXCEPTIONS = "PROPAGATE_EXCEPTIONS"

JWT_KEY = ''.join('b3e8ee7b-bfd8-4e60-9a56-a132b66b8b2c')
JWT_SECRET = "JWT_SECRET_KEY"
